# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
from pathlib import Path
import sys
import numpy as np
import jax.numpy as jnp


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--in_mag_npz",
        type=str,
        default="actuation_mag_manip.npz",
        help="NPZ generated by export_mag_manip_actuation.py (must contain key 'P').",
    )
    parser.add_argument(
        "--actuation_table_pkl",
        type=str,
        default=str(
            (
                Path(__file__).resolve().parents[1]
                / "offline_interpolation_data/actuation_tables/actuation_table.pkl"
            ).resolve()
        ),
    )
    parser.add_argument("--out", type=str, default="actuation_jax_interpolated.npz")
    parser.add_argument("--batch", type=int, default=4096)
    args = parser.parse_args()

    here = Path(__file__).resolve().parent
    repo_root = here.parents[2]
    supiee_dir = here.parents[1]

    sys.path.insert(0, str(repo_root))
    sys.path.insert(0, str(supiee_dir))


    from supiee_auto_diff.actuation_interpolator_jax import load_actuation_table, interpolate_A_vmap

    in_path = Path(args.in_mag_npz).resolve()
    if not in_path.exists():
        raise FileNotFoundError(f"Missing {in_path}. Run export_mag_manip_actuation.py first.")

    payload = np.load(in_path, allow_pickle=True)
    P = np.asarray(payload["P"], dtype=np.float64)

    pkl_path = Path(args.actuation_table_pkl).resolve()
    if not pkl_path.exists():
        raise FileNotFoundError(f"Missing {pkl_path}. Build it with supiee_auto_diff/build_actuation_table.py")

    table = load_actuation_table(pkl_path)

    N = P.shape[0]
    A_jax = np.empty((N, 8, 8), dtype=np.float64)
    bs = int(args.batch)

    for s in range(0, N, bs):
        e = min(N, s + bs)
        A_blk = interpolate_A_vmap(
            table.A_table,
            table.xs,
            table.ys,
            table.zs,
            jnp.asarray(P[s:e], dtype=table.xs.dtype),
        )
        A_jax[s:e] = np.asarray(A_blk, dtype=np.float64)

    out_path = Path(args.out).resolve()
    np.savez(
        out_path,
        P=P,
        A_jax=A_jax,
        in_mag_npz=str(in_path),
        actuation_table_pkl=str(pkl_path),
    )

    print("saved:", out_path)
    print("P:", P.shape, "A_jax:", A_jax.shape)


if __name__ == "__main__":
    main()
